name: flutter_maplibre_gl
repository: https://github.com/maplibre/flutter-maplibre-gl

packages:
  - packages/*

ignore:
  # e.g. ignore example apps
  - 'packages/**/example'

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: |
      Run all static analysis checks
      - Analyze the project for Dart analysis issues.
      - Requires `pub global activate tuneup`.

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: dart pub global run flutter_plugin_tools format
    description: |
      activate flutter_plugin_tools
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `clang-format` (can be installed via Brew on macOS).
       
  # Coverage
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      flutter test --coverage

  # Check pubspecs are valid and publishable in each package.
  lint:pub: >
    melos exec -c 5 --fail-fast --no-private --ignore="*example*" -- \
      pub publish --dry-run
