include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # remove once git dependencies have been removed
    invalid_dependency: ignore

linter:
  rules:
    overridden_fields: false
    avoid_print: false