const layerTypes = [
  "symbol",
  "circle",
  "line",
  "fill",
  "fill-extrusion",
  "raster",
  "hillshade",
  "heatmap",
];
const sourceTypes = [
  "vector",
  "raster",
  "raster_dem",
  "geojson",
  "video",
  "image"
];

const renamedIosProperties = {
  "iconImage": "iconImageName",
  "iconRotate": "iconRotation",
  "iconSize": "iconScale",
  "iconKeepUpright": "keepsIconUpright",
  "iconTranslate": "iconTranslation",
  "iconTranslateAnchor": "iconTranslationAnchor",
  "iconAllowOverlap": "iconAllowsOverlap",
  "iconIgnorePlacement": "iconIgnoresPlacement",
  "textTranslate": "textTranslation",
  "textTranslateAnchor": "textTranslationAnchor",
  "textIgnorePlacement": "textIgnoresPlacement",
  "textField": "text",
  "textFont": "textFontNames",
  "textSize": "textFontSize",
  "textMaxWidth": "maximumTextWidth",
  "textJustify": "textJustification",
  "textMaxAngle": "maximumTextAngle",
  "textWritingMode": "textWritingModes",
  "textRotate": "textRotation",
  "textKeepUpright": "keepsTextUpright",
  "textAllowOverlap": "textAllowsOverlap",
  "symbolAvoidEdges": "symbolAvoidsEdges",
  "circleTranslate": "circleTranslation",
  "circleTranslateAnchor": "circleTranslationAnchor",
  "circlePitchScale": "circleScaleAlignment",
  "lineTranslate": "lineTranslation",
  "lineTranslateAnchor": "lineTranslationAnchor",
  "lineDasharray": "lineDashPattern",
  "fillAntialias": "fillAntialiased",
  "fillTranslate": "fillTranslation",
  "fillTranslateAnchor": "fillTranslationAnchor",
  "rasterHueRotate": "rasterHueRotation",
  "rasterResampling": "rasterResamplingMode",
  "visibility": "isVisible",
  "rasterBrightnessMin": "minimumRasterBrightness",
  "rasterBrightnessMax": "maximumRasterBrightness",
  "fillExtrusionTranslate": "fillExtrusionTranslation",
  "fillExtrusionTranslateAnchor": "fillExtrusionTranslationAnchor",
  "fillExtrusionVerticalGradient": "fillExtrusionHasVerticalGradient",
};

const dartTypeMappingTable = {
  "string": "String",
  "array": "List",
  "number": "double",
  "enum": "String",
  "promoteId": "String",
  "boolean": "bool",
  "*": "Object"
};

const swiftTypeMappingTable = {
  "string": "String",
  "array": "Array",
  "number": "Double",
  "enum": "String",
  "promoteId": "String",
  "boolean": "Bool",
  "*": "Object"
};

const renamedExpressions = {
  "var": "varExpression",
  "in": "inExpression",
  "case": "caseExpression",
  "to-string": "toStringExpression",
  "+": "plus",
  "*": "multiply",
  "-": "minus",
  "%": "percent",
  ">": "larger",
  ">=": "largerOrEqual",
  "<": "smaller",
  "<=": "smallerOrEqual",
  "!=": "notEqual",
  "==": "equal",
  "/": "divide",
  "^": "xor",
  "!": "not",
};