name: sharemap_maplibre_gl_example
publish_to: none
description: Minimal example app for the sharemap_maplibre_gl package.
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  sharemap_maplibre_gl:
    path: ..

dev_dependencies:
  very_good_analysis: 10.0.0

flutter:
  uses-material-design: true
