name: Generate docs

on:
  push:
    # branches: [ main ]

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Install dartdoc
        run: flutter pub global activate dartdoc
      
      - name: Generate docs
        run: flutter pub global run dartdoc

      - name: Push docs
        uses: actions-x/commit@v2
        with:
          name: Docs Bot
          message: "docs: ${{ github.event.commits[0].message }}"
          files: doc
