name: Flutter Beta CI

on:
  schedule: [ cron:  '0 0 * * *' ]
  workflow_dispatch:

jobs:
  build-android:
    name: "Build Android apk"
    uses: ./.github/workflows/_build.yml
    with:
      platform: android
      flutter-channel: beta

  build-ios:
    name: "Build iOS package"
    uses: ./.github/workflows/_build.yml
    with:
      platform: ios
      flutter-channel: beta

  build-web:
    name: "Build web"
    uses: ./.github/workflows/_build.yml
    with:
      platform: web
      flutter-channel: beta
