name: Publish a package to pub.dev

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory of the package to publish
        required: true
        type: string

permissions:
  id-token: write

jobs:
  publish:
    name: 'Publish to pub.dev'
    permissions:
      id-token: write # This is required for requesting the OIDC
    runs-on: ubuntu-latest
    if: github.repository_owner == 'maplibre'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: flutter pub get
        # --force skips the y/N confirmation
      - name: Publish to pub.dev
        run: flutter pub publish --force
